
name: Build and Deploy Project
on: # push / pull_request on master branch
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  builder:  # unity builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    - uses: actions/cache@v4
      with:
        path: /Library
        key: Library-WebGL
        restore-keys: Library-
    - uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL
    - name: List artifact directory contents
      run: ls -R ${{ github.workspace }}
    - uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path:  /home/runner/work/rats/rats/build/WebGL/WebGL
        
  # Deployment job
  deploy:
    needs: builder
    runs-on: ubuntu-latest
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages # this needs to be named this to work
      url: ${{ steps.deployment.outputs.page_url }} # this is the URL of the deployed site
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  # Prints the contents of the artifact directory
  list:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: List artifact directory contents
      run: ls -R ${{ github.workspace }}
  # /home/runner/work/rats/rats/build/WebGL/WebGL:

