name: Test Build

# runs on all branches
on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  # unity builder
  test-builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    - uses: actions/cache@v4
      with:
        path: /Library
        key: Library-WebGL
        restore-keys: Library-
    - uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL